### PR TITLE
QoL Improvements

### PR DESCRIPTION
**Pull request by Cracko298**
## Features of this PR:
- Added a C++ implementation of the 'min_video' module, because I thought it was a little slow.
- Added Progress Bar, and Estimated time till completion in the Python Variation of CLI.
- No rework of the Module was conducted.
- Pre-compiled C++ Binary *.dll and Source is included in the newly created ".\cpp" folder.
- Binary is easily callable through 'ctypes' Library.

### Compile Information:
```
Compiler:            MinGW w64
C++ Version:         C++ 11
Out Binary Type:     min_video.dll
Source File:         min_video.cpp
Build Command:       > g++ -shared -o min_video.dll -O3 -s min_video.cpp
```

### CODE REVIEW

**Comment by Wolfyxon** [comment]
Binaries shouldn't be in the source code. Delete the DLL please.
Also the `__pycache__` dir. Consider using `git` instead of uploading files via GitHub so the `.gitignore` file is respected.

**Comment by Cracko298** [comment]
I'm submitting this through my Phone.
Bad idea on my part 🤣, will update as soon as I can.

**Comment by Cracko298** [comment]
Branch should be able to merge now, sorry about that.
Updated .gitnore to match main repo.

**Comment by Wolfyxon** [comment]
Alright I'll do some testing now. Oh also, the `get_rgb_data()` function is unnecessary since the `pixels` property is public.

**Comment by Cracko298** [comment]
Yes, I noticed the `pixels` property is publicly callable, and able to be referenced.
This added function was apart of a parser to get color data, and reconstruct an image from a frame in the MinVideo Format.
I took it out due to it being unusable in it's current state and most code relating to it.

**Comment by Wolfyxon** [comment]
Alright, all good. 
Merging, thanks.

**Pull request merged**
