### PR TITLE
Updated JS to actually invert properly.

### PR DESCRIPTION
**Pull request by ghost**
Color was inverted when uncheck, and not inverted when checked.
I fixed this problem.

### CODE REVIEW

**Comment by Cracko298** [comment]
If you used my MinImage tool to convert to and from MinVideo, it was no longer in spec with the MinVideo format.
This has been changed in the most recent update. `2.0`.

This means that the Invert Button is correct, however older spec videos won't run properly and need to be inverted in order to run.

**Comment by Wolfyxon** [comment]
My bad

**Comment by Wolfyxon** [comment]
I misinterpreted the diff (I was in a bit of a rush, sorry if that's unprofessional).

The issue is that you played a video of an older MinVideo format, recently the color channel order was inverted to be RGB instead of the OpenCV's BGR.

I'll update the example videos to the new format.

**Comment by Cracko298** [comment]
> I misinterpreted the diff (I was in a bit of a rush).
> 
> The issue is that you played a video of an older MinVideo format, recently the color channel order was inverted to be RGB instead of the OpenCV's BGR.
> 
> I'll update the example videos to the new format.

Yeah, I just updated MinVideo Tools to only use RGB instead of BGR.
I remembered them working, and realized it switched somewhere lately.

**Comment by Wolfyxon** [comment]
I inverted the existing `race.minv` video and also added `two.minv`

**Pull request merged**
