### PR TITLE
Added MinImage Image Format

### PR DESCRIPTION
**Pull request by Cracko298**
MinImage is a format that takes frames from MinVideo and Converts them to a unique image format.
It does some math to do it, added struct (a default python module) to 'min_video'.

### CODE REVIEW

**Comment by Wolfyxon** [comment]
You did a really good job but I think this should be a separate project.
This repo is meant only for a video format.

**Comment by Cracko298** [comment]
Huh, I was just thinking it'd be fine because it's the Frame of the Video rather than traditional images.
I understand however.

**Comment by Wolfyxon** [comment]
Well it does follow the MinVideo philosophy but also adds a bunch of header data which makes it almost a separate format.

I'm unsure.

**Comment by Cracko298** [comment]
Yeah, maybe it'd be a better idea as a tool for MinVideo or something of the sort

**Pull request closed without merging**
